"""HTML generation for the Twitter Digest."""

import re
from datetime import datetime
from pathlib import Path

from .models import DailyDigest


def markdown_to_html(markdown_text: str) -> str:
    """Convert markdown to HTML."""
    html = markdown_text

    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)

    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"__(.+?)__", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
    html = re.sub(r"_(.+?)_", r"<em>\1</em>", html)
    html = re.sub(r"`(.+?)`", r"<code>\1</code>", html)

    html = re.sub(r"\[(.+?)\]\((.+?)\)", r'<a href="\2">\1</a>', html)

    lines = html.split("\n")
    result = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                result.append("<ul>")
                in_list = True
            item = stripped[2:]
            result.append(f"  <li>{item}</li>")
        elif re.match(r"^\d+\.\s", stripped):
            if not in_list:
                result.append("<ul>")
                in_list = True
            item = re.sub(r"^\d+\.\s", "", stripped)
            result.append(f"  <li>{item}</li>")
        else:
            if in_list:
                result.append("</ul>")
                in_list = False
            if stripped and not stripped.startswith("<h"):
                if stripped.startswith("---") or stripped.startswith("***"):
                    result.append("<hr>")
                elif stripped:
                    result.append(f"<p>{stripped}</p>")
            else:
                result.append(stripped)

    if in_list:
        result.append("</ul>")

    return "\n".join(result)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - {date}</title>
    <style>
        :root {{
            --bg: #0d1117;
            --fg: #c9d1d9;
            --accent: #58a6ff;
            --muted: #8b949e;
            --border: #30363d;
            --card-bg: #161b22;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
            background: var(--bg);
            color: var(--fg);
            line-height: 1.6;
            padding: 2rem;
            max-width: 800px;
            margin: 0 auto;
        }}
        header {{
            border-bottom: 1px solid var(--border);
            padding-bottom: 1.5rem;
            margin-bottom: 2rem;
        }}
        h1 {{ color: #fff; font-size: 2rem; margin-bottom: 0.5rem; }}
        .date {{ color: var(--muted); font-size: 0.9rem; }}
        .handles {{ color: var(--muted); font-size: 0.85rem; margin-top: 0.5rem; }}
        h2 {{ color: var(--accent); margin: 2rem 0 1rem; font-size: 1.4rem; }}
        h3 {{ color: #fff; margin: 1.5rem 0 0.75rem; font-size: 1.1rem; }}
        p {{ margin-bottom: 1rem; }}
        ul {{ margin: 0.5rem 0 1rem 1.5rem; }}
        li {{ margin-bottom: 0.5rem; }}
        a {{ color: var(--accent); text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        code {{
            background: var(--card-bg);
            padding: 0.2rem 0.4rem;
            border-radius: 4px;
            font-size: 0.9em;
        }}
        hr {{ border: none; border-top: 1px solid var(--border); margin: 2rem 0; }}
        strong {{ color: #fff; }}
        .content {{ background: var(--card-bg); padding: 1.5rem; border-radius: 8px; }}
        nav {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); }}
        nav a {{ margin-right: 1rem; }}
        footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.8rem; }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <div class="date">{date}</div>
        <div class="handles">Tracking: {handles}</div>
    </header>
    <main class="content">
        {content}
    </main>
    <nav>
        <a href="index.html">← All Digests</a>
    </nav>
    <footer>
        Generated by Twitter Digest
    </footer>
</body>
</html>
"""

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        :root {{
            --bg: #0d1117;
            --fg: #c9d1d9;
            --accent: #58a6ff;
            --muted: #8b949e;
            --border: #30363d;
            --card-bg: #161b22;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
            background: var(--bg);
            color: var(--fg);
            line-height: 1.6;
            padding: 2rem;
            max-width: 800px;
            margin: 0 auto;
        }}
        h1 {{ color: #fff; font-size: 2rem; margin-bottom: 0.5rem; }}
        .subtitle {{ color: var(--muted); margin-bottom: 2rem; }}
        .digest-list {{ list-style: none; }}
        .digest-list li {{
            background: var(--card-bg);
            padding: 1rem 1.5rem;
            border-radius: 8px;
            margin-bottom: 0.75rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}
        .digest-list a {{ color: var(--accent); text-decoration: none; font-weight: 500; }}
        .digest-list a:hover {{ text-decoration: underline; }}
        .digest-list .meta {{ color: var(--muted); font-size: 0.85rem; }}
        footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.8rem; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p class="subtitle">Daily AI-powered summaries of tweets from people you follow</p>
    <ul class="digest-list">
        {digest_links}
    </ul>
    <footer>
        Powered by GitHub Actions + Gemini 2.5 Flash
    </footer>
</body>
</html>
"""


def build_digest_html(
    digest: DailyDigest,
    output_dir: str,
    title: str = "Twitter Digest",
) -> str:
    """Build HTML page for a daily digest. Returns the filename."""
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)

    date_str = digest.date.strftime("%Y-%m-%d")
    filename = f"{date_str}.html"
    filepath = path / filename

    handles_str = ", ".join(f"@{h.handle}" for h in digest.handles) if digest.handles else "None"
    content_html = markdown_to_html(digest.raw_markdown) if digest.raw_markdown else "<p>No content available.</p>"

    html = HTML_TEMPLATE.format(
        title=title,
        date=digest.date.strftime("%A, %B %d, %Y"),
        handles=handles_str,
        content=content_html,
    )

    filepath.write_text(html)
    return filename


def build_index_html(
    output_dir: str,
    title: str = "Twitter Digest",
) -> None:
    """Build index.html listing all digests."""
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)

    digest_files = sorted(path.glob("2*.html"), reverse=True)

    links = []
    for f in digest_files[:30]:
        date_str = f.stem
        try:
            date_obj = datetime.strptime(date_str, "%Y-%m-%d")
            display_date = date_obj.strftime("%A, %B %d, %Y")
        except ValueError:
            display_date = date_str

        links.append(
            f'<li><a href="{f.name}">{display_date}</a></li>'
        )

    if not links:
        links.append("<li>No digests yet. Check back tomorrow!</li>")

    html = INDEX_TEMPLATE.format(
        title=title,
        digest_links="\n        ".join(links),
    )

    (path / "index.html").write_text(html)
